# Generated by Django 4.2.5 on 2023-10-29 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ejsapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='mark',
            field=models.CharField(max_length=5),
        ),
        migrations.CreateModel(
            name='Date',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ejsapp.subject')),
            ],
        ),
        migrations.AddField(
            model_name='mark',
            name='date',
            field=models.ForeignKey(default=12.05, on_delete=django.db.models.deletion.CASCADE, to='ejsapp.date'),
            preserve_default=False,
        ),
    ]
